stages:
  - download-revit-api
  - build
  - sign
  - publish

download-revit-api:
  stage: download-revit-api
  image: alpine:3.12
  variables:
    REVIT_API_URL: https://cdn.bim.ag/revit/2021/RevitAPI.dll
    REVIT_API_CHECKSUM: b5081483584d7f15297c7985936a9d5870a66d89959ac7cc803a528b4836ab30
    REVIT_APIUI_URL: https://cdn.bim.ag/revit/2021/RevitAPIUI.dll
    REVIT_APIUI_CHECKSUM: efc5731f64974aeb526ffcaaf7775a4ef0122cf41cf09f71241517c49edfabac
    GIT_STRATEGY: none
  script:
    - apk add --update --no-cache curl
    - mkdir revit-api
    - |
        echo "${REVIT_API_CHECKSUM}  -" > /tmp/checksum \
        && curl -L "${REVIT_API_URL}" \
        | tee revit-api/RevitAPI.dll \
        | sha256sum -c /tmp/checksum
    - |
        echo "${REVIT_APIUI_CHECKSUM}  -" > /tmp/checksum \
        && curl -L "${REVIT_APIUI_URL}" \
        | tee revit-api/RevitAPIUI.dll \
        | sha256sum -c /tmp/checksum
  artifacts:
    paths:
      - revit-api/
    expire_in: 1 day

build:
  stage: build
  tags:
    - shared-windows
    - windows
    - windows-1809
  dependencies:
    - download-revit-api
  variables:
    LOOKUP_CONFIGURATION: "2021"
    LOOKUP_SOLUTION: CS/RevitLookup.sln
    PATH_BUILD_TOOLS: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin
  before_script:
    - $env:Path += ";${PATH_BUILD_TOOLS}"
    - choco install netfx-4.8-devpack -y
  script:
    - >
      msbuild
      -p:Configuration=${LOOKUP_CONFIGURATION}
      -p:ReferencePath="../revit-api"
      -p:PostBuildEvent=
      ${LOOKUP_SOLUTION}
    - if (-not $?) { throw "Build failed" }

    - mkdir artifacts
    - cp "CS/bin/${LOOKUP_CONFIGURATION}/RevitLookup.dll" artifacts/
    - cp "CS/RevitLookup.addin" artifacts/
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 day

sign:
  stage: sign
  image: debian:buster-slim
  dependencies:
    - build
  variables:
    ASSEMBLY: artifacts/RevitLookup.dll
    TIMESERVER: http://timestamp.digicert.com
    DEBIAN_FRONTEND: noninteractive
    GIT_STRATEGY: none
  script:
    - apt-get update && apt-get install -y --no-install-recommends osslsigncode
    - mkdir -p .secrets && mount -t ramfs -o size=1M ramfs .secrets/
    - echo "${CODESIGN_CERTIFICATE}" | base64 --decode > .secrets/authenticode.spc
    - echo "${CODESIGN_KEY}" | base64 --decode > .secrets/authenticode.key
    - osslsigncode -h sha1 -spc .secrets/authenticode.spc -key .secrets/authenticode.key -t ${TIMESERVER} -in "${ASSEMBLY}" -out "${ASSEMBLY}-sha1"
    - osslsigncode -nest -h sha2 -spc .secrets/authenticode.spc -key .secrets/authenticode.key -t ${TIMESERVER} -in "${ASSEMBLY}-sha1" -out "${ASSEMBLY}"
    - rm "${ASSEMBLY}-sha1"
  after_script:
    - rmdir .secrets
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 day
  only:
    variables:
      - $CODESIGN_CERTIFICATE != null
      - $CODESIGN_KEY != null

publish:
  stage: publish
  image: alpine:3.12
  dependencies:
    - sign
  variables:
    GIT_STRATEGY: none
  before_script:
    - |
        if [ -n "${CI_COMMIT_TAG}" ]; then
            export RELEASE_NAME="${CI_COMMIT_TAG}"
            export S3_FOLDER="releases"
        else
            export RELEASE_NAME="${CI_COMMIT_BRANCH}-$(date --utc -Iseconds)"
            export S3_FOLDER="current"
        fi
    - export ZIP="${RELEASE_NAME}.7z"

    - apk add --update --no-cache curl jq py-pip p7zip
    - pip install awscli
    - eval $(aws ecr get-login --no-include-email --region $AWS_REGION | sed 's|https://||')
  script:
    - 7z a "${ZIP}" ./artifacts/*
    - aws s3 cp "${ZIP}" "s3://${S3_BUCKET_NAME}/${S3_FOLDER}/${ZIP}"
  only:
    variables:
      - $AWS_ACCESS_KEY_ID != null
      - $AWS_SECRET_ACCESS_KEY != null
      - $AWS_REGION != null
      - $S3_BUCKET_NAME != null
