name: 📃 Documentation Issue
description: Report issues in our documentation
labels:
  - documentation 📃
  - unverified ⌛
body:
  - type: textarea
    attributes:
      label: Provide a description of requested docs changes
      placeholder: Briefly describe which document needs to be corrected and why
    validations:
      required: true
